# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RCPPColMean <- function(x) {
    .Call('_SurveyEdaPackage_RCPPColMean', PACKAGE = 'SurveyEdaPackage', x)
}

RCPPColMedian <- function(x) {
    .Call('_SurveyEdaPackage_RCPPColMedian', PACKAGE = 'SurveyEdaPackage', x)
}

RCPPColSD <- function(x) {
    .Call('_SurveyEdaPackage_RCPPColSD', PACKAGE = 'SurveyEdaPackage', x)
}

RCPPColMax <- function(x) {
    .Call('_SurveyEdaPackage_RCPPColMax', PACKAGE = 'SurveyEdaPackage', x)
}

RCPPColMin <- function(x) {
    .Call('_SurveyEdaPackage_RCPPColMin', PACKAGE = 'SurveyEdaPackage', x)
}

RCPPColSkew <- function(x) {
    .Call('_SurveyEdaPackage_RCPPColSkew', PACKAGE = 'SurveyEdaPackage', x)
}

